### ISSUE TITLE
Formation links in collections display don't work

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#125]
When you click on a dot and look at the text about a collection, stratigraphic names look like links, but they go nowhere.

**Comment by Loznerol** [comment]
Hi, I was wondering if I could take a look at this issue?

**Comment by mmcclenn** [comment]
Thank you for reminding me to take a look at this. This issue is now fixed. Clicking on a stratigraphic name in the description of a collection now adds a filter that will display only collections associated with that stratum. You can then click on the 'x' to remove the filter and once again display the entire set of collections.
