### ISSUE TITLE
link to "classic" collection details page from collection modal

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/navigator#53]
Need to first know how to format links to pages in the Wing system

**Comment by mmcclenn** [comment]
The URL pattern is: '/classic/basicCollectionSearch?collection_no=' + collection_no

When extracting the numeric part from the collection identifier, I would suggest using a regular expression to extract (\d+) rather than trying to delete characters. This approach will be more robust in case we need to change the identifier syntax at any point.
