### ISSUE TITLE
When Navigator is using data 1.2, not all collections are plotted.

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#56]
I tried Dinosauria, Jurassic, and it shows only 26 collections. There should be about 1560.

![jurassic dinosauria 1 2](https://cloud.githubusercontent.com/assets/19557452/25185965/c10f4b4e-24ec-11e7-80dd-9d3dbc8389ab.jpeg)

**Comment by markuhen** [comment]
Something VERY strange is happening here. When you zoom in, MORE dots appear, and the number of collections goes UP!

**Comment by vjpsyverson** [comment]
@markuhen, that is because when you zoom in, it changes the "level" value
passed to colls/summary, and the number of clusters changes. The number of
dots SHOULD increase when you zoom in, because each dot represents fewer
collections. However, the number of collections should of course decrease!

The problem seems to be in the data service "colls/summary". Using the
exact same call, 1.1 correctly reports
<https://paleobiodb.org/data1.1/colls/summary.json?lngmin=-180&lngmax=180&latmin=-90&latmax=90&limit=all&show=time&level=2&interval_id=15&base_id=52775>
1672 collections and 3346 occurrences for Jurassic Dinosauria, but 1.2
incorrectly
reports
<https://paleobiodb.org/data1.2/colls/summary.json?lngmin=-180&lngmax=180&latmin=-90&latmax=90&limit=all&show=time&level=2&interval_id=15&base_id=52775>
only 28 and 50, respectively. The same thing happens for other values of
the "level" parameter (in fact, for level=1, 1.2 reports nothing at all).
That is, 1.2 seems to be returning only a subset of the clusters it should
return.

**Comment by vjpsyverson** [comment]
@mmcclenn do you know what's up here?

**Comment by markuhen** [comment]
No. There should be big dots that resolve into smaller dots. The big dots don't plot on the zoomed out map. The number of collections in the window should NOT be the number of dots seen on the map, but the number of underlying collections shown on the map. I do not think that the number should change zoomed in or zoomed out.

**Comment by markuhen** [comment]
Just to be clear, the way it used to work was fine. It does not work that way any  more.

**Comment by mmcclenn** [comment]
Fixed, I think. Please test, and make sure I am not missing anything.

**Comment by markuhen** [comment]
This does indeed look like it is working now.

**Comment by mmcclenn** [comment]
Then I will mark this as closed. Yay!
