### ISSUE TITLE
Taxon list error

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/navigator#89]
I clicked on a dot in Navigator and got a list of taxa. When I clicked on one of the clickable taxa, I got the error below. I'm not really sure what it is supposed to do, but this is definitely not it!

![list json error](https://user-images.githubusercontent.com/19557452/29038842-12fbe878-7b77-11e7-83de-726afe9ca2bb.jpeg)

**Comment by vjpsyverson** [comment]
This is not broken on training. I am trying to figure out what's wrong with it on phylum.

**Comment by markuhen** [comment]
Yes it is broken on training. It is just broken differently. In Training, it does nothing when you click on the taxon. It should be doing SOMETHING.

**Comment by jczaplew** [comment]
@markuhen - are you experiencing this when you click on all collections or just certain ones?

**Comment by markuhen** [comment]
This happens on all the ones I have tried.

**Comment by jczaplew** [comment]
From what I can tell, it only seems to happen when you click on a genus or species - anything higher and it seems to work. My guess is that there is an issue in the template, because the data service request that fires off is missing the `nam` parameter - `https://paleobiodb.org/data1.2/taxa/list.json?name=&show=seq`

**Comment by vjpsyverson** [comment]
@markuhen, that's weird, what browser are you using? Because when I click the taxon name in the occurrences tab on training, it correctly adds a taxon filter and closes the modal (this is in Chrome). And that includes the exact example in your screenshot. 

@jczaplew, taxa/list is hit only at line 1635 of navMap.js (in navMap.filterByTaxon), and when I add a console.log to that line it reports correctly. Again, though, this is the version on training, and is hitting the dev version of the data service on teststrata.

**Comment by markuhen** [comment]
I am seein this in Safari Version 10.1.2 (12603.3.8)

**Comment by vjpsyverson** [comment]
I need someone with Safari to test this for me, then, as I don't have anything that runs OS X anymore.

**Comment by vjpsyverson** [comment]
@jczaplew, I'm testing this again and I can't replicate the missing name parameter error. When I do exactly what Mark describes in the original report (on the Aro locality, in the Neogene right on top of Lagos), the taxa/list call I get is correctly formed: `https://paleobiodb.org/data1.2/taxa/list.json?name=Carcharocles%20megalodon&show=seq`
Can you test this on Safari for me if you have a minute?

**Comment by markuhen** [comment]
I just tested this. It is now working properly on Training, but I get the error on the main server. 

Thus, I think this is fixed and just needs to be pushed to the live site next time we do a push!
